### ISSUE TITLE
希望能支持1.17.1版本

### ISSUE THREAD

**Issue by VCMellon** [TartaricAcid/BakaDanmaku#15]
希望能支持1.17.1版本

**Comment by FLYEMOJ1** [comment]
求更新呜呜呜

**Comment by qwq-2020** [comment]
我想要fabric...

**Comment by Yesterday17** [comment]
这东西核心机制和forge没有半毛钱关系，和forge搭边的只有个config、command和显示弹幕的event，你们完全可以来pr的（

**Comment by TartaricAcid** [comment]
好久没关注这个仓库，所以一些反馈没来得及回复：
1.17 已经完成，可以去：https://www.mcmod.cn/download/3120.html 下载

PS： @Yesterday17 配置文件也没用 Forge 的，自己手搓的 JSON 格式的
