### ISSUE TITLE
1.18 Port

### ISSUE THREAD

**Issue by VulpesStella** [TartaricAcid/BakaDanmaku#16]
https://github.com/FractalMC/BakaDanmaku/tree/1.18
:D

**Comment by lizheyo77** [comment]
> https://github.com/FractalMC/BakaDanmaku/tree/1.18 :D

未来有希望支持Fabric1.18吗

**Comment by VulpesStella** [comment]
> > https://github.com/FractalMC/BakaDanmaku/tree/1.18 :D
> 
> 未来有希望支持Fabric1.18吗

有时间试试，我觉得不会很难

**Comment by Hanmingxuan** [comment]
Fabric1.18 Please

**Comment by lizheyo77** [comment]
> > > https://github.com/FractalMC/BakaDanmaku/tree/1.18 :D
> > 
> > 
> > 未来有希望支持Fabric1.18吗
> 
> 有时间试试，我觉得不会很难

非常感谢 迫切需要 求求了xd

**Comment by MikhailTapio** [comment]
> 

好了:D
https://github.com/FractalMC/BakaDanmaku/releases/tag/1.18-fabric

**Comment by VulpesStella** [comment]
> > > > https://github.com/FractalMC/BakaDanmaku/tree/1.18 :D
> > > 
> > > 
> > > 未来有希望支持Fabric1.18吗
> > 
> > 
> > 有时间试试，我觉得不会很难
> 
> 非常感谢 迫切需要 求求了xd

好了
https://github.com/FractalMC/BakaDanmaku/releases/tag/1.18-fabric

**Comment by lizheyo77** [comment]
> > > > > https://github.com/FractalMC/BakaDanmaku/tree/1.18 :D
> > > > 
> > > > 
> > > > 未来有希望支持Fabric1.18吗
> > > 
> > > 
> > > 有时间试试，我觉得不会很难
> > 
> > 
> > 非常感谢 迫切需要 求求了xd
> 
> 好了 https://github.com/FractalMC/BakaDanmaku/releases/tag/1.18-fabric

谢谢大哥 一生平安 太感谢了呜呜呜

**Comment by TartaricAcid** [comment]
已经完成，可以去：https://www.mcmod.cn/download/3120.html 下载
