### ISSUE TITLE
Game Crash in 1.19.2

### ISSUE THREAD

**Issue by ShulkerSakura** [TartaricAcid/BakaDanmaku#17]
plz update

**Comment by Aya-Net** [comment]
i have already commited a pr  to support 1.19.x

**Comment by TartaricAcid** [comment]
Been busy lately, but will update soon

**Comment by TartaricAcid** [comment]
~~都是国人吧（我也只在国内发布这模组，也只支持 B 站）我直接中文回复~~
已经更新到了 1.19.2，直接使用最新版即可
