### ISSUE TITLE
[Bug]重进存档弹幕姬有概率不释放线程

### ISSUE THREAD

**Issue by Haocen2004** [TartaricAcid/BakaDanmaku#8]
RT，有时候会重复接受消息，有时候会导致mc占用爆炸，详情咨询plus （溜）
鬼知道还维护么顺手提交issues算了

**Comment by kevinluo6188** [comment]
鬼知道还维护么+1

**Comment by Haocen2004** [comment]
有生之年竟然维护了
但看起来还是没管issues
不过重写估计没问题了
